-- 코드를 작성해주세요
-- ROOT 아이템의 PARENT 아이템 ID는 NULL
-- 아이템 ID, 아이템명 출력
-- 아이템 ID 오름차순
SELECT II.ITEM_ID, II.ITEM_NAME
FROM ITEM_INFO AS II
INNER JOIN ITEM_TREE AS IT
ON II.ITEM_ID=IT.ITEM_ID
WHERE IT.PARENT_ITEM_ID IS NULL
ORDER BY II.ITEM_ID;