-- 코드를 입력하세요
WITH result AS(
    SELECT ai.ANIMAL_ID AS ID, ao.ANIMAL_ID, ao.Name
    FROM ANIMAL_INS AS ai
    RIGHT JOIN ANIMAL_OUTS AS ao
    ON ai.ANIMAL_ID=ao.ANIMAL_ID
)
SELECT ANIMAL_ID, NAME FROM result
WHERE ID IS NULL
ORDER BY ANIMAL_ID;
