-- 코드를 입력하세요
SELECT fh.FLAVOR FROM FIRST_HALF AS fh
INNER JOIN ICECREAM_INFO AS ii
ON fh.FLAVOR = ii.FLAVOR 
    AND fh.TOTAL_ORDER >= 3000 
    AND ii.INGREDIENT_TYPE = "fruit_based"
ORDER BY fh.TOTAL_ORDER DESC;