-- 코드를 입력하세요
-- 2022년 10월에 작성된
-- 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일
-- 댓글 작성일 기준 오름차순, 게시글 제목 기준 오름차순
SELECT UGB.TITLE, UGB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, DATE_FORMAT(UGR.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE 
FROM USED_GOODS_REPLY AS UGR
INNER JOIN USED_GOODS_BOARD AS UGB
ON UGR.BOARD_ID = UGB.BOARD_ID
WHERE UGB.CREATED_DATE LIKE "2022-10%"
ORDER BY UGR.CREATED_DATE, UGB.TITLE;

